CREATE TABLE IF NOT EXISTS public.User (
    ID UUID NOT NULL PRIMARY KEY,
    NAME CHARACTER VARYING NOT NULL,
    EMAIL CHARACTER VARYING NOT NULL,
    PHONE CHARACTER VARYING,
    BIRTH_DATE DATE,
    PASSWORD CHARACTER VARYING NOT NULL,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_DATE TIMESTAMP,
    UPDATED_DATE TIMESTAMP
);

CREATE TABLE IF NOT EXISTS public.Role (
    ID UUID NOT NULL PRIMARY KEY,
    ROLE_NAME CHARACTER VARYING NOT NULL
);

CREATE TABLE IF NOT EXISTS public.User_Role (
    ID_ROLE UUID NOT NULL,
    ID_USER UUID NOT NULL,

    FOREIGN KEY (ID_ROLE) REFERENCES public.Role(id),
    FOREIGN KEY (ID_USER) REFERENCES public.User(id),

    CONSTRAINT USER_ROLE_PK PRIMARY KEY (ID_USER, ID_ROLE)
);