CREATE TABLE IF NOT EXISTS public.Badge (
    ID             UUID                NOT NULL PRIMARY KEY,
    NAME           CHARACTER VARYING   NOT NULL,
    MIN_POINT      INTEGER             NOT NULL,
    POSITION       INTEGER             NOT NULL,
    IS_ACTIVE      BOOLEAN             DEFAULT TRUE,
    CREATED_DATE   TIMESTAMP,
    UPDATED_DATE   TIMESTAMP
);

CREATE TABLE IF NOT EXISTS public.Promotion (
    ID              UUID               NOT NULL PRIMARY KEY,
    NAME            CHARACTER VARYING  NOT NULL,
    REQUIRED_POINTS INTEGER            NOT NULL,
    COUPON_CODE     CHARACTER VARYING
);