CREATE TABLE IF NOT EXISTS public.Occurrence (
    ID                UUID                NOT NULL PRIMARY KEY,
    TYPE              CHARACTER VARYING   NOT NULL,
    SEVERITY          CHARACTER VARYING   NOT NULL,
    STATUS            CHARACTER VARYING   NOT NULL,
    DESCRIPTION       CHARACTER VARYING,
    LATITUDE          DOUBLE PRECISION    NOT NULL,
    LONGITUDE         DOUBLE PRECISION    NOT NULL,
    ADDRESS           CHARACTER VARYING,
    REPORTED_AT       TIMESTAMP           NOT NULL,
    RESOLVED_AT       TIMESTAMP,
    VALIDATED         BOOLEAN             NOT NULL DEFAULT FALSE,
    REPORTER_USER_ID  UUID                NOT NULL,
    RESOLVED_BY_USER  UUID,
    CONSTRAINT FK_OCC_REPORTER
        FOREIGN KEY (REPORTER_USER_ID) REFERENCES public.User(ID),
    CONSTRAINT FK_OCC_RESOLVER
        FOREIGN KEY (RESOLVED_BY_USER) REFERENCES public.User(ID)
);