CREATE TABLE IF NOT EXISTS public.Media (
    ID             UUID               NOT NULL PRIMARY KEY,
    OCCURRENCE_ID  UUID               NOT NULL,
    MEDIA_TYPE     CHARACTER VARYING  NOT NULL,
    URL            CHARACTER VARYING  NOT NULL,
    CREATED_AT     TIMESTAMP          NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_MEDIA_OCCURRENCE FOREIGN KEY (OCCURRENCE_ID) REFERENCES public.Occurrence(ID)
);
